dependency:
  name: galaxy
  enabled: no
prerun: no
driver:
  name: docker
platforms:
  - name: {{ cookiecutter.role_name }}-test-${MOLECULE_DISTRIBUTION:-centos8}
    image: "quay.io/samdoran/${MOLECULE_DISTRIBUTION:-centos8}-ansible:latest"
    command: ${MOLECULE_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: yes
    pre_build_image: yes
provisioner:
  name: ansible
  config_options:
    defaults:
      stdout_callback: ansible.posix.debug
      show_task_path_on_failure: yes
      force_color: yes
  playbooks:
    converge: ${MOLECULE_PLAYBOOK:-converge.yml}
scenario:
  name: default
verifier:
  name: ansible
